---
# tasks file for sigma.wait-up

- name: wait for ssh to be up
  local_action:
    module: wait_for
    args:
      host: "{{ ansible_host | default(ansible_ssh_host | default(inventory_hostname)) }}"
      port: "{{ ansible_port | default(ansible_ssh_port | default (22)) }}"
      search_regex: "{{ ssh_banner_regex }}"
